-- ════════════════════════════════════════════════════════════════════════════
-- MIGRACIÓN DE BASE DE DATOS — ARTERIS
-- Ejecutar en Supabase → SQL Editor → New query → pegar todo → Run.
-- Es seguro ejecutarlo más de una vez (usa IF NOT EXISTS).
-- ════════════════════════════════════════════════════════════════════════════

-- 1) Columna para recuperación de contraseña de médicos
ALTER TABLE medicos   ADD COLUMN IF NOT EXISTS reset_token text;

-- 2) Columna para recuperación de contraseña de pacientes (por las dudas)
ALTER TABLE pacientes ADD COLUMN IF NOT EXISTS reset_token text;

-- 3) Tabla de eventos adversos / clínicos reportados
CREATE TABLE IF NOT EXISTS eventos_adversos (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_paciente text NOT NULL,
    descripcion    text NOT NULL,
    reportado_por  text DEFAULT 'paciente',
    fecha          timestamptz DEFAULT now()
);

-- 4) Tabla de alertas generadas automáticamente
CREATE TABLE IF NOT EXISTS alertas (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_paciente text NOT NULL,
    tipo           text,
    mensaje        text NOT NULL,
    fecha          timestamptz DEFAULT now()
);

-- 5) Índices para acelerar las consultas por paciente
CREATE INDEX IF NOT EXISTS idx_eventos_codigo  ON eventos_adversos(codigo_paciente);
CREATE INDEX IF NOT EXISTS idx_alertas_codigo  ON alertas(codigo_paciente);

-- ════════════════════════════════════════════════════════════════════════════
-- FIN DE LA MIGRACIÓN
-- ════════════════════════════════════════════════════════════════════════════
